stages:
  - build
  - deploy

variables:
  FF_NETWORK_PER_BUILD: "true"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

inlab_plus:
  image: docker:cli
  stage: build
  tags:
    - not_ir
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin  "$CI_REGISTRY"
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}/inlab_plasmic:${CI_COMMIT_BRANCH}" -f ./.build/Dockerfile .
    - docker push "${CI_REGISTRY_IMAGE}/inlab_plasmic:${CI_COMMIT_BRANCH}"

bridge-deploy:
  stage: deploy
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  inherit:
    variables: false
  trigger: 
    project: synappsgroup/inlab
    branch: dev
    strategy: depend
