inlab_plasmic:
  extends: .ci_default
  before_script:
    - !reference [.before_script_default, before_script]
    - cd inlab_plasmic

  script:
    - docker build
      -t "${CI_REGISTRY_IMAGE}/inlab_plasmic:${CI_COMMIT_BRANCH}"
      -f ./.build/Dockerfile .

    - docker push "${CI_REGISTRY_IMAGE}/inlab_plasmic:${CI_COMMIT_BRANCH}"
